name: Publish Docker image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # schedule:
  #  - cron:  '0 2 * * *'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hermannsblum/website:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
